### PR TITLE
Revive project, bring it to the 1.x world

### PR DESCRIPTION
**Pull request by aviks**
Tests pass locally, let's see what CI says. 

Overrides #143 and  #144. Incorporates #139.

TODO: move to jll and 1.3

### CODE REVIEW

**Comment by aviks** [comment]
I'll merge this now. Thanks @bkamins and @ararslan for getting us halfway there, even if it's taken two more years to complete this!

I'll register the current state to be compatible with 1.0, and then change to jll packages with a minimum 1.3 requirement.

**Comment by aviks** [comment]
Close #134. Close #135. Close #140. Close #143. Close #144. Close #145.

**Comment by timholy** [comment]
Miracles do happen after all!

**Comment by aviks** [comment]
Just need a little faith, that's all! 🤣

**Pull request merged**
