### PR TITLE
fix julia 0.5 deprecations

### PR DESCRIPTION
**Pull request by bjarthur**

### CODE REVIEW

**Comment by bjarthur** [comment]
anyone know what happened to `LambdaInfo` in julia 0.6?

also, for Tk to support julia 0.3, we need to discuss what to do about Base.Text.

**Comment by bjarthur** [comment]
i should add that otherwise the tests pass on julia 0.4 and 0.5

**Comment by bjarthur** [comment]
re. Base.Text see https://github.com/JuliaGraphics/Tk.jl/issues/117 and https://github.com/JuliaGraphics/Tk.jl/issues/103

**Comment by timholy** [comment]
Let's drop 0.3 support---can you bump REQUIRE and .travis.yml?

Re 0.6, sorry, I haven't had time to follow the latest developments.

Give me the word and I'll tag Tk, Winston, and ImageView all at the same time.

**Comment by bjarthur** [comment]
0.3 dropped.  ready to tag.

**Pull request merged**
