### PR TITLE
Switch CI and doc building to github actions

### LINKED ISSUE #153: There's no documentation
There is no documentation over at [https://juliahub.com/docs/Tk/BVfq8/0.7.0/](https://juliahub.com/docs/Tk/BVfq8/0.7.0/ )

### PR DESCRIPTION
**Pull request by LilithHafner**
Fixes #153

### CODE REVIEW

**Comment by LilithHafner** [comment]
This may also need an admin to adjust gh-pages settings in this github repo.

**Comment by ViralBShah** [comment]
I'm happy to do it if someone can give me admin.  Perhaps we can also have Lilith be admin?

Pinging @SimonDanisch @timholy

**Comment by timholy** [comment]
I've sent invites to you both

**Comment by ViralBShah** [comment]
@LilithHafner I merged just to try and fix up a few things.

**Comment by ViralBShah** [comment]
When https://github.com/JuliaPackaging/Yggdrasil/pull/9120 and https://github.com/JuliaPackaging/Yggdrasil/pull/9121 are merged, we should be able to test mac aarch64 as well.

**Pull request merged**
