### PR TITLE
Compat update for String rename

### PR DESCRIPTION
**Pull request by StefanKarpinski**
I'm seeing test failures but I don't think they're related.

### CODE REVIEW

**Comment by yuyichao** [comment]
Requires Compat version bump.

Please follow up on your PR. The first comment about having to bump Compat version is made a few hours ago yet none of the new PR's have that problem fixed.

**Comment by StefanKarpinski** [comment]
> Please follow up on your PR. The first comment about having to bump Compat version was made a few hours ago yet none of the new PR's have that problem fixed.

I've been making PRs, not checking email. Feel free to make a PR based off of my PR if you're dying to fix it.

**Comment by yuyichao** [comment]
I'm not dying to fix it, I just don't want to see packages rapidly being broken on 0.4

**Comment by StefanKarpinski** [comment]
Then don't merge the PR until it gets fixed.

**Comment by yuyichao** [comment]
I suppose @tkelman can comment on the effect of opening a lot of misleading PR's.

**Comment by JeffBezanson** [comment]
I don't really understand what this debate is about.

**Pull request merged**
